In [ ]:
The principle behind nearest neighbor methods is to find a predefined  number of training samples closest 
in distance to the new point, and predict the label from these.it is a a non-parametric method.In classification 
we find out the maximum classes under  predifine neaibours (k=33 ,3 ,4 etc) ,and in regression we find out the avarage 
distance  

t can be used in superviced (regression,classification) and unsuperviced (k-nn clastering) learning  
Despite its simplicity, nearest neighbors has been successful in a large number of classification and regression problems


In [ ]:
It is use for when N < 10,000

In [ ]:
1.)Before fitting the model we should taake care of outlaiers and imbalance data set.

2.)KNN classifier predicts the class of a given test observation by identifying the observations that are nearest to it, 
the scale of the variables matters. Any variables that are on a large scale will have a much larger effect on the distance 
between the observations,and hence on the KNN classifier, than variables that are on a small scale.

3.)Regarding the Nearest Neighbors algorithms, if two neighbors  and  have identical distances but different labels, 
the result will depend on the ordering of the training data.

In [ ]:
Nearest Neighbors

In [ ]:
 Unsupervised Nearest Neighbors typically use to Finding the distance between Neighbors no succh application,

In [2]:
from sklearn.neighbors import NearestNeighbors
import numpy as np
X = np.array([[-1, -1], [-2, -1], [-3, -2], [1, 1], [2, 1], [3, 2]])
nbrs = NearestNeighbors(n_neighbors=2, algorithm='ball_tree').fit(X)


In [3]:
distances, indices = nbrs.kneighbors(X)

In [4]:
distances #the nearest neighbor of each point (ex [-1,-1]) is the point itself, at a distance of zero

array([[0.        , 1.        ],
       [0.        , 1.        ],
       [0.        , 1.41421356],
       [0.        , 1.        ],
       [0.        , 1.        ],
       [0.        , 1.41421356]])

In [9]:
nbrs.kneighbors_graph(X).toarray()

array([[1., 1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0.],
       [0., 1., 1., 0., 0., 0.],
       [0., 0., 0., 1., 1., 0.],
       [0., 0., 0., 1., 1., 0.],
       [0., 0., 0., 0., 1., 1.]])

In [6]:
indices

array([[0, 1],
       [1, 0],
       [2, 1],
       [3, 4],
       [4, 3],
       [5, 4]], dtype=int64)

In [ ]:
Nearest Neighbors Classifier

In [ ]:
 KNeighborsClassifier and  RadiusNeighborsClassifier

In [ ]:
KNeighborsClassifier
the most commonly used technique. 
The optimal choice of the value  is highly data-dependent.
Larger  suppresses the effects of noise, but makes the classification boundaries less distinct.

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=4)
knn.fit(X_train,y_train)
pred = knn.predict(X_test)

In [ ]:
RadiusNeighborsClassifier
where the data is not uniformly sampled RadiusNeighborsClassifier can be a better choice.
The user specifies a fixed radius , such that points in scattered neighborhoods use fewer nearest neighbors for the classification.
For high-dimensional parameter spaces, this method becomes less effective due to the so-called “curse of dimensionality”.

In [ ]:
from sklearn.neighbors import RadiusNeighborsClassifier
neigh = RadiusNeighborsClassifier(radius=1.0)
knn.fit(X_train,y_train)
pred = neigh.predict(X_test)

In [ ]:
Predictions and Evaluations

In [ ]:
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.model_selection import cross_val_score
print(confusion_matrix(y_test,pred))
print(classification_report(y_test,pred))

In [ ]:
Nearest Neighbors Regressor

In [ ]:
Neighbors-based regression can be used in cases where the data labels are continuous rather than discrete variables. 
The label assigned to a query point is computed based on the mean of the labels of its nearest neighbors

In [ ]:
KNeighborsRegressor and RadiusNeighborsRegressor

In [ ]:
RadiusNeighborsRegressor 

In [ ]:
from sklearn.neighbors import RadiusNeighborsRegressor
neig_r = RadiusNeighborsRegressor(radius=1.0)
neig_r.fit(X_train,y_train)
pred = neig_r.predict(X_test)

In [ ]:
KNeighborsRegressor 

In [ ]:
from sklearn.neighbors import KNeighborsRegressor
K_neigh_r = KNeighborsRegressor(n_neighbors=2)
K_neigh_r(X_train,y_train)
pred = K_neigh_r.predict(X_test)

In [ ]:
Predictions and Evaluations

In [ ]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
print(r2_score(y_true, y_pred))
print(mean_squared_error(y_true, y_pred)) #mse
print(mean_squared_error(y_true, y_pred, squared=False)) #RSME

In [ ]:
Parameterss

In [ ]:
Choosing a K Value

In [ ]:
n_neighborsint, default=5
Number of neighbors to use by default for kneighbors queries.

In [ ]:
weights{‘uniform’, ‘distance’} or callable, default=’uniform’

In [ ]:
the impact of nearest neighbors on the test point should be more than  the  further awaay points,

'uniform': uniform weights. All points in each neighborhood are weighted equally.

'distance': weight points by the inverse of their distance.
in this case, closer neighbors of a query point will have a greater influence than neighbors which are further away.
distance increses weight decreases

In [ ]:
algorithm and leaf_size

In [ ]:
'brute' will use brute-force
Efficient brute-force neighbors searches can be very competitive for small data samples.
Brute force query time is unchanged by data structure.
Brute force query time is largely unaffected by the value of K

‘kd_tree’ will use KDTree
KD trees partition data along Cartesian axes,
This is a significant improvement over brute-force for large 
Though the KD tree approach is very fast for low-dimensional D<20  neighbors searches, 
It becomes inefficient as  grows very large: this is one manifestation of the so-called “curse of dimensionality”. 
    
‘ball_tree’ will use BallTree
ball trees partition data in a series of nesting hyper-spheres.
This makes tree construction more costly than that of the KD tree, 
but results in a data structure which can be very efficient on highly structured data, even in very high dimensions.

Ball tree and KD tree query times can be greatly influenced by data structure
Ball tree and KD tree query time will become slower as K increases

the ability to prune branches in a tree-based query is reduced. In this situation, Brute force queries can be more efficient.
where K>N(sample)

leaf_sizeint, default=30
Leaf size passed to BallTree or KDTree. This can affect the speed of the construction and query, 
as well as the memory required to store the tree.
The optimal value depends on the nature of the problem.
    

In [ ]:
metric and p and metric_paramsdict.

In [ ]:
Euclidean /L2 norm /Ridge/ RMS distance : When p = 1, this is equivalent to using manhattan_distance (l1) 
it is written as sqrt(sum((x - y)^2)),do not preffer under the attact of outlaier and also high dimensanality (>5)

Manhattan/ L1 norm/ Lasso/ MA(mean absolute) distance : euclidean_distance (l2) for p = 2, it is written as sum(|x - y|),
do preffer under the attact of outlaier and also high dimensanality (>5)

Minkowski :For arbitrary p (3,4,5 etc), minkowski_distance (l_p) is used,it is written as sum(|x - y|^p)^(1/p) ,
find p by etaration


In [ ]:
metric_paramsdict:Additional keyword arguments for the metric function ,
it is used when CONDITION-1 is used to prepare the model

In [ ]:
'euclidean' sqrt(sum((x - y)^2))

'manhattan' sum(|x - y|)

'chebyshev' max(|x - y|)

'minkowski' sum(|x - y|^p)^(1/p)

'wminkowski' sum(|w * (x - y)|^p)^(1/p)

'seuclidean' sqrt(sum((x - y)^2 / V))

'mahalanobis' sqrt((x - y)' V^-1 (x - y))

In [2]:
from sklearn.metrics import pairwise_distances
from scipy.spatial import distance
c=distance.canberra([1, 0, 0], [0, 1, 0])
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1,weights='distance',algorithm='brute', metric='mahalanobis')
knn = KNeighborsClassifier(n_neighbors=1,weights='distance',algorithm='brute',metric_params='c')

In [47]:
X = [[0], [1], [2], [3]]
y = [0, 0, 1, 1]
c=distance.canberra(X,2)
neigh1 = KNeighborsClassifier(n_neighbors=2)
neigh2= KNeighborsClassifier(n_neighbors=2,weights='distance',algorithm='brute', metric='mahalanobis')
neigh3= KNeighborsClassifier(n_neighbors=1,weights='distance',algorithm='brute',metric='seuclidean')
X1 = [[1.3], [1], [0], [3]]

In [48]:
neigh1.fit(X,y)

KNeighborsClassifier(n_neighbors=2)

In [49]:
neigh2.fit(X,y)

KNeighborsClassifier(algorithm='brute', metric='mahalanobis', n_neighbors=2,
                     weights='distance')

In [50]:
neigh3.fit(X,y)

KNeighborsClassifier(algorithm='brute', metric='seuclidean', n_neighbors=1,
                     weights='distance')

In [51]:
pred1 = neigh3.predict(X1)

D:\m y python\enviourment\anaconda\lib\site-packages\sklearn\metrics\pairwise.py:1447: FutureWarning: from version 0.25, pairwise_distances for metric='seuclidean' will require V to be specified if Y is passed.
  warnings.warn("from version 0.25, pairwise_distances for "


In [52]:
pred1

array([0, 0, 0, 1])

In [53]:
pred

array([0, 0, 0, 1])

In [10]:
neigh1.fit(X, y)
neigh2.fit(X, y)


KNeighborsClassifier(algorithm='brute', metric='mahalanobis', n_neighbors=2,
                     weights='distance')

In [ ]:
CONDITION-1
algorithm = 'auto' selects 'brute' if any of the following conditions are verified:

input data is sparse

metric = 'precomputed'

D>15

K>=N/2 find by itearation 

effective_metric_ isn’t in the VALID_METRICS list for either 'kd_tree' or 'ball_tree'

In [ ]:
it selects the first out of 'kd_tree' and 'ball_tree' that has effective_metric_ in its VALID_METRICS list. 
It is based on the following assumptions:

the number of query points /test points is at least the same order as the number of training points

leaf_size is close to its default value of 30

when D>15 the intrinsic dimensionality of the data is generally too high for tree-based methods
    

In [ ]:
The actual performance is highly dependent on the structure of the training data.
Datasets used in machine learning tend to be very structured, and are very well-suited for tree-based queries.

In [ ]:
Choosing a K Value
n_neighborsint, default=5
Number of neighbors to use by default for kneighbors queries.

In [ ]:
Classifier

In [ ]:

from sklearn.model_selection import cross_val_score
accuracy_rate = []
# Will take some time
for i in range(1,40):
    knn = KNeighborsClassifier(n_neighbors=i)
    score=cross_val_score(knn,df_feat,df['TARGET CLASS'],cv=10)
    accuracy_rate.append(score.mean())

In [ ]:
plt.figure(figsize=(10,6))
#plt.plot(range(1,40),error_rate,color='blue', linestyle='dashed', marker='o',
  #       markerfacecolor='red', markersize=10)
plt.plot(range(1,40),accuracy_rate,color='blue', linestyle='dashed', marker='o',
         markerfacecolor='red', markersize=10)
plt.title('Error Rate vs. K Value')
plt.xlabel('K')
plt.ylabel('accuracy_rate')

In [ ]:
#Regressor (use explained_variance_score ,RSME OR R2 )

In [ ]:

from sklearn.metrics import explained_variance_score
RSME = []
# Will take some time
for i in range(1,40):
    
    knn = KNeighborsClassifier(n_neighbors=i)
    score=mean_squared_error(df_feat,df['TARGET CLASS'])
    RSME.append(score)

In [ ]:
plt.figure(figsize=(10,6))
#plt.plot(range(1,40),error_rate,color='blue', linestyle='dashed', marker='o',
  #       markerfacecolor='red', markersize=10)
plt.plot(range(1,40),RSME,color='blue', linestyle='dashed', marker='o',
         markerfacecolor='red', markersize=10)
plt.title('RSME vs. K Value')
plt.xlabel('K')
plt.ylabel('RSME')